service: snake
plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate

custom:
  hostedZoneName: snake.eve.game.com
  cloudfrontInvalidate:
    distributionId: 'E3OCPEBC3M4UYX' #conditional, distributionId or distributionIdKey is required.
    distributionIdKey: 'E3OCPEBC3M4UYX' #conditional, distributionId or distributionIdKey is required.
    items: # one or more paths required
      - '/*'
  s3Sync:
    - bucketName: ${self:custom.hostedZoneName}
      localDir: build

provider:
  region: us-east-1
  name: aws
  stage: ${opt:stage, 'dev'}
  environment:
    bucketName: ${self:custom.hostedZoneName}
resources:
  Resources:
    StaticWebSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.hostedZoneName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    CDN:
      Type: "AWS::CloudFront::Distribution"

    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticWebSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "StaticWebSite"
                    },
                    "/*"
                  ]
                ]
  Outputs:
    CDNDistributionId:
      Description: CDN distribution id.
      Value:
        Ref: CDN

