name: "Build"
on:
    push:
        branches:
            - "main"
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - uses: actions/checkout@v2

            - run: yarn install --frozen-lockfile
            - run: yarn deploy


